version: "3"
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - database

  database:
    image: oscarfonts/h2:latest
    ports:
      - 1521:1521
      - 81:81
    volumes:
      - ./h2-data:/h2-data